name: CI/CD — Build, Push & Deploy

on:
  push:
    branches: [ "test" ]
    paths-ignore:
          - 'README.md'
          - '.gitignore'
          - '.gitattributes'

permissions:
  id-token: write
  contents: read

jobs:
  build-infra:
    runs-on: ubuntu-latest
    outputs:
      server-ip: ${{steps.tf.outputs.SERVER_IP}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials via OIDC (Terraform)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::075091538636:role/github-node-oicd # Change this to your role ARN
          aws-region: us-east-1

      - name: Deploy EC2 Instance
        working-directory: ./terraform
        env:
          TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        run: |
          terraform init
          terraform plan -out=tfplan
          terraform apply -auto-approve tfplan

      - name: Get server IP
        id: tf
        working-directory: ./terraform
        run: echo "SERVER_IP=$(terraform output -raw server_ip)" >> $GITHUB_OUTPUT
